In [8]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# Dummy data (matriks peringkat pengguna terhadap item)
user_item_ratings = np.array([
    [5, 4, 0, 0, 1],
    [0, 5, 4, 0, 2],
    [3, 0, 0, 4, 4],
    [0, 2, 5, 4, 0],
])

# Fungsi untuk menghitung kesamaan antar pengguna menggunakan Cosine Similarity
def user_similarity(ratings):
    return cosine_similarity(ratings)

# Fungsi untuk membuat rekomendasi berdasarkan user-based collaborative filtering
def user_based_recommendation(user_ratings, similar_users, k=2):
    weighted_sum = np.zeros(user_ratings.shape[1])
    similarity_sum = 0

    # Pilih k pengguna terdekat
    top_users = np.argsort(similar_users)[-k-1:-1][::-1]

    for user in top_users:
        # Hitung bobot kesamaan antar pengguna
        weight = similar_users[user]

        # Hitung jumlah bobot kesamaan
        similarity_sum += weight

        # Hitung jumlah tertimbang peringkat pengguna
        weighted_sum += weight * user_ratings[user]

    # Prediksi peringkat untuk item yang belum dinilai
    predicted_ratings = weighted_sum / similarity_sum

    return predicted_ratings

# Contoh penggunaan
user_similarities = user_similarity(user_item_ratings)
user_id = 0  # Pengguna yang ingin diberikan rekomendasi
predicted_ratings = user_based_recommendation(user_item_ratings, user_similarities[user_id])

print("Peringkat prediksi untuk pengguna", user_id, ":", predicted_ratings)


Peringkat prediksi untuk pengguna 0 : [1.42501885 2.62496858 2.09997487 1.90002513 2.95001257]


In [9]:
import numpy as np

def user_similarity(data_matrix):
    similarity_matrix = np.dot(data_matrix, data_matrix.T)
    norm_matrix = np.sqrt(np.sum(data_matrix**2, axis=1, keepdims=True))
    similarity_matrix /= np.dot(norm_matrix, norm_matrix.T)
    return similarity_matrix

def item_similarity(data_matrix):
    similarity_matrix = np.dot(data_matrix.T, data_matrix)
    norm_matrix = np.sqrt(np.sum(data_matrix**2, axis=0, keepdims=True))
    similarity_matrix /= np.dot(norm_matrix.T, norm_matrix)
    return similarity_matrix

def predict_ratings(data_matrix, similarity_matrix):
    return np.dot(similarity_matrix, data_matrix) / np.sum(np.abs(similarity_matrix), axis=1, keepdims=True)

# Contoh data ekspresi gen (baris = sampel, kolom = gen)
data_matrix = np.array([
    [1.2, 0.8, 0.0, 1.5],
    [0.0, 2.0, 1.8, 0.6],
    [1.5, 0.0, 0.9, 1.2],
    [0.8, 1.2, 1.5, 0.0]
])

# Menghitung similarity antar sampel
user_similarity_matrix = user_similarity(data_matrix)

# Menghitung similarity antar gen
item_similarity_matrix = item_similarity(data_matrix)

# Prediksi ekspresi gen yang belum diukur
predicted_ratings = predict_ratings(data_matrix, user_similarity_matrix)

# Output hasil
print("Similarity Matrix (User-Based):")
print(user_similarity_matrix)
print("\nSimilarity Matrix (Item-Based):")
print(item_similarity_matrix)
print("\nPredicted Ratings:")
print(predicted_ratings)


Similarity Matrix (User-Based):
[[1.         0.43580205 0.8155532  0.44341801]
 [0.43580205 1.         0.40013156 0.88903617]
 [0.8155532  0.40013156 1.         0.57768352]
 [0.44341801 0.88903617 0.57768352 1.        ]]

Similarity Matrix (Item-Based):
[[1.         0.37420147 0.48823168 0.85966855]
 [0.37420147 1.         0.87251258 0.48365083]
 [0.48823168 0.87251258 1.         0.42761799]
 [0.85966855 0.48365083 0.42761799 1.        ]]

Predicted Ratings:
[[1.03090833 0.81777036 0.8102977  1.01683697]
 [0.67317764 1.25340291 1.28209593 0.6362863 ]
 [1.05278301 0.76822162 0.89023782 0.95347569]
 [0.75550614 1.14524022 1.24398934 0.65006166]]
